# Server's host address and port. Set ip empty to use public address
bind:
  ip: 'localhost'
  port: 65535

# Spawn position in the world
spawnPosition:
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

# Bossbar sends when player join to server
bossBar:
  enable: true
  text: '{"text": "Welcome to the Limbo!"}'
  health: 1.0
  # Available colors: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
  color: PINK
  # Available divisions: SOLID, DASHES_6, DASHES_10, DASHES_12, DASHES_20
  division: SOLID

# Player info forwarding support. Available types: NONE, LEGACY, MODERN
# Don't use secret if you not use MODERN type
infoForwarding:
  type: NONE
  secret: '<YOUR_SECRET_HERE>'

# Read timeout for connections in milliseconds
readTimeout: 30000

# Define debug level. On release, i recommend to use 0 level, since
# there are many useless for release information about ping, received packets, etc.
# Levels:
# 0 - Display only useful info
# 1 - Display info and some debug
# 2 - Display info and warnings
# 3 - Display info, warnings, errors
debugLevel: 3

# Warning! Do not touch params of this block, if you not completely sure what is this!
netty:
  # Use Linux native transport type, if it possible
  useEpoll: true
  # EventLoopGroup threads count
  threads:
    bossGroup: 1
    workerGroup: 4